#!/usr/bin/env python2.7

import sys
import os.path
dev_path = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', '..'))
sys.path.insert(0, dev_path)

import gevent

import rpipe.config.log
import rpipe.client
import rpipe.exceptions

for c in rpipe.client.connect_gen():
#    print("Received connection.")
#
#    c.write("Data from client.")
#
    print("Entering read loop.")
    while 1:
#        received = c.read()
#        print("Received from server: %s" % (received,))
#        print("Received something.")
        gevent.sleep(1)
