#!/usr/bin/env python2.7

import sys
import os.path
dev_path = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', '..'))
sys.path.insert(0, dev_path)

import gevent

import rpipe.config.log
import rpipe.server.connection

s = rpipe.server.connection.Server()
gevent.spawn(s.run)

# TODO(dustin): Start web-server, here.

while 1:
    gevent.sleep(1)
