#!/usr/bin/env python

import sys
import os
dev_path = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', '..'))
sys.path.insert(0, dev_path)

import rpipe
root_path = os.path.abspath(os.path.join(os.path.dirname(rpipe.__file__), '..'))

os.chdir(root_path)

working_directory = os.environ.get('RP_GUNICORN_PATH', '/usr/local/bin')
gunicorn_filepath = os.path.join(working_directory, 'gunicorn')

import subprocess
cmd = [gunicorn_filepath, '-c', 'rpipe/resources/data/gunicorn_conf_server_prod.py', 'rpipe.app.wsgi_server:wsgi']
p = subprocess.Popen(cmd, env=os.environ)
r = p.wait()
if r != 0:
    raise EnvironmentError("Gunicorn launch failed.")
